"""
Learning stub.

Intended to update KB/vector store from successful executions and user feedback.
"""

from __future__ import annotations

import json
import uuid
from pathlib import Path
from typing import Dict, List

from agent.state import AgentState
from knowledge.retriever import clear_knowledge_cache

KB_PATH = Path(__file__).with_name("knowledge_base.json")

def learn(state: AgentState) -> AgentState:
    # Placeholder for future policy-driven learning from AgentState.
    return state


def _load_kb() -> Dict:
    """
    Load the knowledge base JSON file.

    Structure (new format):
      {
        "version": "0.1.0",
        "description": "...",
        "rules": [
          {
            "intent": "<query>",
            "command": "<cmd>",
            "description": "...",
            "examples": [...]
          }
        ]
      }
    """
    if not KB_PATH.exists():
        return {"version": "0.1.0", "description": "Knowledge base", "rules": []}

    try:
        with KB_PATH.open("r", encoding="utf-8") as f:
            data = json.load(f)
    except (OSError, json.JSONDecodeError):
        return {"version": "0.1.0", "description": "Knowledge base", "rules": []}

    if not isinstance(data, dict):
        return {"version": "0.1.0", "description": "Knowledge base", "rules": []}

    # Ensure proper structure
    if "rules" not in data:
        data["rules"] = []
    if "version" not in data:
        data["version"] = "0.1.0"
    if "description" not in data:
        data["description"] = "Knowledge base"

    return data


def _save_kb(kb: Dict) -> None:
    KB_PATH.parent.mkdir(parents=True, exist_ok=True)
    with KB_PATH.open("w", encoding="utf-8") as f:
        json.dump(kb, f, indent=2, ensure_ascii=False)
        f.write("\n")


def save_command(query: str, commands: List[str]) -> None:
    """
    Persist generated commands into knowledge_base.json so the agent learns over time.

    Uses the new format with rules array:
    {
      "version": "0.1.0",
      "description": "...",
      "rules": [
        {
          "intent": "<query>",
          "command": "<cmd>",
          "description": "Generated by LLM",
          "examples": []
        }
      ]
    }
    """
    cleaned_query = (query or "").strip()
    if not cleaned_query:
        return

    cmds = [c.strip() for c in commands or [] if isinstance(c, str) and c.strip()]
    if not cmds:
        return

    kb = _load_kb()
    rules = kb.get("rules") or []

    # Add each command as a separate rule
    for cmd in cmds:
        # Check if this command already exists for this query
        existing_rule = None
        for rule in rules:
            if rule.get("intent") == cleaned_query and rule.get("command") == cmd:
                existing_rule = rule
                break

        # If not found, add new rule
        if not existing_rule:
            new_rule = {
                "id": str(uuid.uuid4()),
                "intent": cleaned_query,
                "command": cmd,
                "description": "Generated by LLM",
                "examples": [],
                "text": cleaned_query,
                "embedding": [],
            }
            rules.append(new_rule)

    kb["rules"] = rules
    _save_kb(kb)
    clear_knowledge_cache()

